---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-operator
  namespace: openshift-storage
spec:
  channel: "4.3"
  name: local-storage-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
